name: Release

on:
  push:
    tags:
    - "v*.*.*"

jobs:
  Release:
    name: Release
    env:
      NPM_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
      CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Install
      run: npm install
    - name: Coverage
      run: npm run coverage
    - name: Upload
      run: npm run codecov
    - name: Build
      run: ls && npm run build && ls
    - name: AUTH
      run: ls && echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc && ls
    - name: Publish
      run: ls && npm publish --access public && ls
