on: push
jobs:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
      - name: Install
        run: npm install
      - name: Test
        run: npm run coverage
        run: npm run codecov

on: tags
jobs:
  name: Test
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
    - name: Install
      run: npm install
    - name: Test
      run: npm run coverage
      run: npm run codecov
  name: release
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
    - name: Install
      run: npm publish --access public
          
