on: push
name: CI
jobs:
  all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
      - name: Install
        run: npm install
      - name: Test
        run: npm test
      - name: Publish
        if: github.ref == 'refs/heads/master'
        uses: mikeal/merge-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          
          